name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [main] # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-20.04
    steps:
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        publish: true
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ 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 }}
        publish_dir: ${{ steps.deployment.outputs.artifact }}
