name: Deploy Sphinx documentation to Pages

on: 
  push:
    branches: [maim] # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser
      - name: Sphinx build
        run: |
          sphinx-build docs _build
      - name: Set up Git
        run: |
         git config --global user.name 'IvanVP1'
         git config --global user.email 'gfdfbjkkjjh@gmail.com'
         git remote set-url origin https://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@github.com/laduga-com/pradis-docs.git
      - name: Deploy to GitHub Pages
        uses: sphinx-notes/pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: main
          personal_token: ${{ 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 }}
          publish_dir: _build/
          force_orphan: true
      - name: Push to gh-pages
        run: |
         git push origin HEAD:gh-pages --force






